CREATE TABLE IF NOT EXISTS quotes (id INTEGER PRIMARY KEY AUTOINCREMENT, quote_key TEXT, project_key TEXT NOT NULL, customer TEXT, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_by TEXT, created_email TEXT, jira_error TEXT, epic_key TEXT, epic_id TEXT, handed_off_at TEXT, handoff_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_quotes_key ON quotes(quote_key);
CREATE INDEX IF NOT EXISTS idx_quotes_epic ON quotes(epic_key);
CREATE TABLE IF NOT EXISTS quote_sections (quote_id INTEGER NOT NULL, discipline TEXT NOT NULL, job_type TEXT, counts TEXT, chips TEXT, novelty TEXT, spec TEXT, best_hours REAL, likely_hours REAL, worst_hours REAL, tech REAL, risk REAL, dep REAL, reference_id TEXT, reference_compare TEXT, estimator_id TEXT, quoted_hours REAL, job_elo REAL, category_id TEXT, updated_at TEXT NOT NULL, PRIMARY KEY (quote_id, discipline));
CREATE TABLE IF NOT EXISTS quote_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, quote_id INTEGER NOT NULL, discipline TEXT NOT NULL, account_id TEXT NOT NULL, requested_by TEXT, note TEXT, status TEXT NOT NULL DEFAULT 'pending', answer TEXT, comment TEXT, jira_commented INTEGER NOT NULL DEFAULT 0, answered_at TEXT, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_quote_requests_account ON quote_requests(account_id, status);
CREATE TABLE IF NOT EXISTS count_checks (category_id TEXT PRIMARY KEY, category_key TEXT, quote_id INTEGER NOT NULL, discipline TEXT, team TEXT, quoted TEXT, actual TEXT, status TEXT NOT NULL DEFAULT 'pending', checked_by TEXT, checked_at TEXT, created_at TEXT NOT NULL);
DELETE FROM sync_state WHERE key = 'category_cursor';
UPDATE completed_jobs SET confidence = CASE WHEN actual_seconds IS NULL OR actual_seconds = 0 THEN 'poor' WHEN estimate_seconds IS NULL OR estimate_seconds = 0 THEN 'partial' WHEN CAST(actual_seconds AS REAL) / estimate_seconds > 10 OR CAST(actual_seconds AS REAL) / estimate_seconds < 0.05 THEN 'partial' ELSE 'good' END;
